name: Build and Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Run Tests (Optional)
        run: npm test # Comment this out if you don't have tests

      - name: Upload Artifact (Save Build Output)
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
